import os

files = [
'python auto-residual-based-N2-0.py&',
'python auto-residual-based-N2-1.py&',
'python auto-residual-based-N2-10.py&',
'python auto-residual-based-N2-11.py&',
'python auto-residual-based-N2-12.py&',
'python auto-residual-based-N2-13.py&',
'python auto-residual-based-N2-14.py&',
'python auto-residual-based-N2-15.py&',
'python auto-residual-based-N2-16.py&',
'python auto-residual-based-N2-17.py&',
'python auto-residual-based-N2-18.py&',
'python auto-residual-based-N2-19.py&',
'python auto-residual-based-N2-2.py&',
'python auto-residual-based-N2-20.py&',
'python auto-residual-based-N2-21.py&',
'python auto-residual-based-N2-22.py&',
'python auto-residual-based-N2-23.py&',
'python auto-residual-based-N2-24.py&',
'python auto-residual-based-N2-25.py&',
'python auto-residual-based-N2-26.py&',
'python auto-residual-based-N2-27.py&',
'python auto-residual-based-N2-28.py&',
'python auto-residual-based-N2-29.py&',
'python auto-residual-based-N2-3.py&',
'python auto-residual-based-N2-4.py&',
'python auto-residual-based-N2-5.py&',
'python auto-residual-based-N2-6.py&',
'python auto-residual-based-N2-7.py&',
'python auto-residual-based-N2-8.py&',
'python auto-residual-based-N2-9.py&',
'python auto-residual-based-O1-0.py&',
'python auto-residual-based-O1-1.py&',
'python auto-residual-based-O1-10.py&',
'python auto-residual-based-O1-11.py&',
'python auto-residual-based-O1-12.py&',
'python auto-residual-based-O1-13.py&',
'python auto-residual-based-O1-14.py&',
'python auto-residual-based-O1-15.py&',
'python auto-residual-based-O1-16.py&',
'python auto-residual-based-O1-17.py&',
'python auto-residual-based-O1-18.py&',
'python auto-residual-based-O1-19.py&',
'python auto-residual-based-O1-2.py&',
'python auto-residual-based-O1-20.py&',
'python auto-residual-based-O1-21.py&',
'python auto-residual-based-O1-22.py&',
'python auto-residual-based-O1-23.py&',
'python auto-residual-based-O1-24.py&',
'python auto-residual-based-O1-25.py&',
'python auto-residual-based-O1-26.py&',
'python auto-residual-based-O1-27.py&',
'python auto-residual-based-O1-28.py&',
'python auto-residual-based-O1-29.py&',
'python auto-residual-based-O1-3.py&',
'python auto-residual-based-O1-4.py&',
'python auto-residual-based-O1-5.py&',
'python auto-residual-based-O1-6.py&',
'python auto-residual-based-O1-7.py&',
'python auto-residual-based-O1-8.py&',
'python auto-residual-based-O1-9.py&',

]

for file in files:
    os.system(file)
    # print file